### ISSUE TITLE
Crear una DashBoard

### ISSUE THREAD

**Issue by MrPokemonYT** [adriabama06/no-soy-un-music-bot#1]
Que permita buscar la música en una misma y administrar el prefix del bot en el servidor en el que el usuario tenga permisos

Y que al poner la música por la DashBoard que el bot revise si la persona que puso la música esta en un canal de voz y si esta en uno y ningún otro usuario lo esta utilizando que se conecte al canal de voz y reproduzca la música

**Comment by adriabama06** [comment]
ok, lo añadire despues de actualizar a typescript y reparar el comando de volumen
